import operator
from typing import Annotated, List, TypedDict

class ResearchState(TypedDict):
    # The original user query
    query: str
    
    # The list of sub-queries generated by the Planner
    plan: List[str]
    
    # Track completed steps and their results: [("search query", "result text")]
    # The operator.add ensures we append to this list as the graph runs
    past_steps: Annotated[List[tuple], operator.add]
    
    # The final synthesized answer
    draft_answer: str
    
    # NEW: Flag to control graph routing
    is_safe: bool